title: 'Blog DaJoana | Cosmética Natural'
email: cosmeticanatural_formacao@dajoana.com
description: >
  Explore artigos e tendências em cosmética natural, com dicas práticas, receitas caseiras e soluções ecológicas para cuidar da sua pele todos os dias.

baseurl: '' # mantém vazio se usares domínio próprio
url: 'https://www.dajoana.com'

# Informação de redes sociais (melhora SEO e Open Graph)
social:
  name: Blog DaJoana
  links:
    - https://www.instagram.com/dajoana_cosmeticaformacao
    - https://www.facebook.com/dajoanacosmeticanatural
    - https://www.tiktok.com/@dajoana_cosmetica

# Idioma e fuso horário globais
lang: pt-PT
timezone: Europe/Lisbon

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2

markdown: kramdown
permalink: /:categories/:title/

pagination:
  enabled: true
  per_page: 5
  permalink: '/blog/page:num/'
  title: ':title - Página :num'
  trail:
    before: 2
    after: 2
  sort_field: 'date'
  sort_reverse: true

defaults:
  - scope:
      path: '' # Aplica a todo o site
      type: 'posts'
    values:
      layout: 'post'
      author: 'Susana Soares da Silva'
      lang: 'pt-PT'
