title: 'Blog DaJoana | Cosmética Natural'
email: cosmeticanatural_formacao@dajoana.com
description: >
  Explore artigos e tendências em cosmética natural, com dicas práticas, receitas caseiras e soluções ecológicas para cuidar da sua pele todos os dias.

baseurl: '' # Importante para GitHub Pages
url: 'https://www.dajoana.com'

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
permalink: /:categories/:title/

collections:
  blog:
    output: true
    permalink: /blog/:title/

defaults:
  - scope:
      path: '' # Aplica-se a todo o site
      type: 'posts'
    values:
      layout: 'post'
      author: 'Susana Soares da Silva'
      category: jekyll
      lang: 'pt-PT'
