title: 'Blog DaJoana | Cosmética Natural'
email: cosmeticanatural_formacao@dajoana.com
description: >
  "Últimos artigos e novidades da cosmética natural"
baseurl: '' # se estiveres a usar GitHub Pages com domínio próprio, mantém vazio
url: 'https://www.dajoana.com'
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
permalink: /:categories/:title/
collections:
  blog:
    output: true
